language: csharp
install:
- nuget restore Snake.sln
script:
- xbuild /p:Configuration=Release Snake.sln
- mono ./packages/NUnit.Runners.Net4.2.6.4/tools/nunit-console.exe
notifications:
  slack: swindp1:qcwDEPxIZoUTSh6N6Qu28ZTi